### ISSUE TITLE
Operation shadowing an external function leads to a crash

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#160]
When trying to reproduce parts of [System C](https://se-tuebingen.github.io/oopsla-2022-artifact/capability/), I got the following error when attempting to shadow `println`:

<img width="912" alt="Screenshot 2022-09-27 at 16 46 00" src="https://user-images.githubusercontent.com/11269173/192559077-8e587f99-c957-4264-8ef7-44e0b730da9e.png">

Also happens when `Console` is an `interface` or when `Console` is renamed to `Konsole`.

**Comment by b-studios** [comment]
Can it be that the problem is that we do not sanitize `console`?

**Comment by b-studios** [comment]
Ok, I reproduced your error. It is actually the shadowing, you are right.

Here is the example as code for easier reference:

```
effect Console { def println(msg: String): Unit }

def myFunction { console: Console } =
  console.println("hello")
```
And here is the stack trace
<details>
```
[info] compiling 68 Scala sources to /Users/jonathan/Desktop/github/effekt-refactor/effekt/jvm/target/scala-3.1.2/classes ...
[info] running effekt.Server bug.effekt
[error] java.lang.ClassCastException: class effekt.symbols.package$BuiltinFunction cannot be cast to class effekt.symbols.package$Operation (effekt.symbols.package$BuiltinFunction and effekt.symbols.package$Operation are in unnamed module of loader sbt.internal.LayeredClassLoader @27e83710)
[error] 	at scala.collection.immutable.List.filter(List.scala:529)
[error] 	at effekt.typer.Typer$.checkOverloadedMethodCall(Typer.scala:903)
[error] 	at effekt.typer.Typer$.checkExpr$$anonfun$1(Typer.scala:184)
[error] 	at effekt.typer.Typer$.checkAgainst$$anonfun$1(Typer.scala:1173)
[error] 	at effekt.util.messages$ErrorReporter.at(Messages.scala:124)
[error] 	at effekt.util.messages$ErrorReporter.at$(Messages.scala:76)
[error] 	at effekt.context.Context.at(Context.scala:38)
[error] 	at effekt.typer.Typer$.checkAgainst(Typer.scala:1180)
[error] 	at effekt.typer.Typer$.checkExpr(Typer.scala:281)
[error] 	at effekt.typer.Typer$.checkStmt$$anonfun$1(Typer.scala:520)
[error] 	at effekt.typer.Typer$.checkAgainst$$anonfun$1(Typer.scala:1173)
[error] 	at effekt.util.messages$ErrorReporter.at(Messages.scala:124)
[error] 	at effekt.util.messages$ErrorReporter.at$(Messages.scala:76)
[error] 	at effekt.context.Context.at(Context.scala:38)
[error] 	at effekt.typer.Typer$.checkAgainst(Typer.scala:1180)
[error] 	at effekt.typer.Typer$.checkStmt(Typer.scala:523)
[error] 	at effekt.typer.Typer$.$anonfun$24$$anonfun$1(Typer.scala:639)
[error] 	at effekt.context.ContextOps.in(Context.scala:28)
[error] 	at effekt.context.ContextOps.in$(Context.scala:17)
[error] 	at effekt.context.Context.effekt$namer$NamerOps$$super$in(Context.scala:38)
[error] 	at effekt.namer.NamerOps.in(Namer.scala:673)
[error] 	at effekt.namer.NamerOps.in$(Namer.scala:659)
[error] 	at effekt.context.Context.in(Context.scala:78)
[error] 	at effekt.typer.Typer$.$anonfun$24(Typer.scala:639)
[error] 	at effekt.typer.TyperOps.bindingAllCapabilities(Typer.scala:1308)
[error] 	at effekt.typer.TyperOps.bindingAllCapabilities$(Typer.scala:1227)
[error] 	at effekt.context.Context.bindingAllCapabilities(Context.scala:38)
[error] 	at effekt.typer.Typer$.$anonfun$20$$anonfun$3(Typer.scala:640)
[error] 	at effekt.typer.TyperOps.withRegion(Typer.scala:1417)
[error] 	at effekt.typer.TyperOps.withRegion$(Typer.scala:1227)
[error] 	at effekt.context.Context.withRegion(Context.scala:38)
[error] 	at effekt.typer.Typer$.$anonfun$20(Typer.scala:659)
[error] 	at effekt.typer.TyperOps.withUnificationScope(Typer.scala:1278)
[error] 	at effekt.typer.TyperOps.withUnificationScope$(Typer.scala:1227)
[error] 	at effekt.context.Context.withUnificationScope(Context.scala:38)
[error] 	at effekt.typer.Typer$.synthDef$$anonfun$1(Typer.scala:660)
[error] 	at effekt.util.messages$ErrorReporter.at(Messages.scala:124)
[error] 	at effekt.util.messages$ErrorReporter.at$(Messages.scala:76)
[error] 	at effekt.context.Context.at(Context.scala:38)
[error] 	at effekt.typer.Typer$.synthDef(Typer.scala:726)
[error] 	at effekt.typer.Typer$.run$$anonfun$1$$anonfun$1$$anonfun$1$$anonfun$2(Typer.scala:65)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:333)
[error] 	at effekt.typer.Typer$.run$$anonfun$1$$anonfun$1$$anonfun$1(Typer.scala:70)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] 	at effekt.typer.TyperOps.withUnificationScope(Typer.scala:1278)
[error] 	at effekt.typer.TyperOps.withUnificationScope$(Typer.scala:1227)
[error] 	at effekt.context.Context.withUnificationScope(Context.scala:38)
[error] 	at effekt.typer.TyperOps.withUnificationScope(Typer.scala:1282)
[error] 	at effekt.typer.TyperOps.withUnificationScope$(Typer.scala:1227)
[error] 	at effekt.context.Context.withUnificationScope(Context.scala:38)
[error] 	at effekt.typer.Typer$.run$$anonfun$1$$anonfun$1(Typer.scala:72)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error] 	at effekt.context.ContextOps.in(Context.scala:28)
[error] 	at effekt.context.ContextOps.in$(Context.scala:17)
[error] 	at effekt.context.Context.effekt$namer$NamerOps$$super$in(Context.scala:38)
[error] 	at effekt.namer.NamerOps.in(Namer.scala:673)
[error] 	at effekt.namer.NamerOps.in$(Namer.scala:659)
[error] 	at effekt.context.Context.in(Context.scala:78)
[error] 	at effekt.typer.Typer$.run$$anonfun$1(Typer.scala:73)
[error] 	at effekt.context.Context.using$$anonfun$1(Context.scala:69)
[error] 	at effekt.context.ContextOps.in(Context.scala:28)
[error] 	at effekt.context.ContextOps.in$(Context.scala:17)
[error] 	at effekt.context.Context.effekt$namer$NamerOps$$super$in(Context.scala:38)
[error] 	at effekt.namer.NamerOps.in(Namer.scala:673)
[error] 	at effekt.namer.NamerOps.in$(Namer.scala:659)
[error] 	at effekt.context.Context.in(Context.scala:78)
[error] 	at effekt.context.Context.using(Context.scala:70)
[error] 	at effekt.typer.Typer$.run(Typer.scala:85)
[error] 	at effekt.typer.Typer$.run(Typer.scala:45)
[error] 	at effekt.Phase$$anon$1.run$$anonfun$1(Phase.scala:56)
[error] 	at scala.Option.flatMap(Option.scala:283)
[error] 	at effekt.Phase$$anon$1.run(Phase.scala:56)
[error] 	at effekt.Phase$$anon$1.run(Phase.scala:56)
[error] 	at effekt.Phase$$anon$1.run(Phase.scala:56)
[error] 	at effekt.Phase$task$2$.run(Phase.scala:75)
[error] 	at effekt.util.Task$.$anonfun$1(Task.scala:144)
[error] 	at effekt.context.Context.withMessages(Context.scala:92)
[error] 	at effekt.util.Task$.compute(Task.scala:145)
[error] 	at effekt.util.Task$.need(Task.scala:174)
[error] 	at effekt.util.Task$.need(Task.scala:165)
[error] 	at effekt.util.Task.apply(Task.scala:29)
[error] 	at effekt.util.Task.apply$(Task.scala:9)
[error] 	at effekt.Phase$task$2$.apply(Phase.scala:73)
[error] 	at effekt.Phase$$anon$2.run(Phase.scala:82)
[error] 	at effekt.Phase$$anon$1.run(Phase.scala:56)
[error] 	at effekt.Phase$$anon$1.run(Phase.scala:56)
[error] 	at effekt.Phase$$anon$1.run(Phase.scala:56)
[error] 	at effekt.Phase.apply(Phase.scala:41)
[error] 	at effekt.Phase.apply$(Phase.scala:34)
[error] 	at effekt.Phase$$anon$1.apply(Phase.scala:54)
[error] 	at effekt.Compiler.compileWhole(Compiler.scala:211)
[error] 	at effekt.Compiler.compileWhole$(Compiler.scala:92)
[error] 	at effekt.context.Context.compileWhole(Context.scala:38)
[error] 	at effekt.Driver.compileSource(Driver.scala:63)
[error] 	at effekt.Driver.compileSource$(Driver.scala:25)
[error] 	at effekt.Server$.compileSource(Server.scala:241)
[error] 	at effekt.Server$.compileSource(Server.scala:241)
[error] 	at kiama.util.Compiler.compileFile(Compiler.scala:117)
[error] 	at kiama.util.Compiler.compileFile$(Compiler.scala:22)
[error] 	at effekt.Server$.compileFile(Server.scala:241)
[error] 	at kiama.util.Compiler.compileFiles$$anonfun$1(Compiler.scala:106)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.immutable.List.foreach(List.scala:333)
[error] 	at kiama.util.Compiler.compileFiles(Compiler.scala:107)
[error] 	at kiama.util.Compiler.compileFiles$(Compiler.scala:22)
[error] 	at effekt.Server$.compileFiles(Server.scala:241)
[error] 	at kiama.util.Compiler.run(Compiler.scala:99)
[error] 	at kiama.util.Compiler.run$(Compiler.scala:22)
[error] 	at effekt.Server$.kiama$util$Server$$super$run(Server.scala:241)
[error] 	at effekt.Server$.kiama$util$Server$$super$run(Server.scala:241)
[error] 	at kiama.util.Server.run(Server.scala:38)
[error] 	at kiama.util.Server.run$(Server.scala:21)
[error] 	at effekt.Server$.effekt$Driver$$super$run(Server.scala:241)
[error] 	at effekt.Driver.run(Driver.scala:43)
[error] 	at effekt.Driver.run$(Driver.scala:25)
[error] 	at effekt.Server$.run(Server.scala:241)
[error] 	at effekt.Server$.run(Server.scala:241)
[error] 	at kiama.util.Compiler.driver(Compiler.scala:92)
[error] 	at kiama.util.Compiler.driver$(Compiler.scala:22)
[error] 	at effekt.Server$.driver(Server.scala:241)
[error] 	at kiama.util.Compiler.main(Compiler.scala:56)
[error] 	at kiama.util.Compiler.main$(Compiler.scala:22)
[error] 	at effekt.Server$.main(Server.scala:241)
[error] 	at effekt.Server.main(Server.scala)
[error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
```
</details>
