### ISSUE TITLE
Compiled JS code fails when executed

### ISSUE THREAD

**Issue by IR0NSIGHT** [effekt-lang/effekt#311]
When writing the bounce benchmark, i found a compiler bug.
commenting out this line, makes the compiled js file fail upon execution:
 "       val random = next();"

I am using a fresh install of effekt 0.2.1 (latest master as of now)

The effekt code runs fine with 
```sh
 effekt.sh examples/fasteffekt/bounce.effekt 
```
## Trigger the bug
WHEN i comment out the line marked with " //FIXME: uncommenting this line breaks the compiler."
AND THEN run it again
THEN it compiles without error 
BUT fails when executing the js code.
```sh
max-priv@NOAH367-L:~/Dokumente/repos/effekt$ effekt.sh examples/fasteffekt/bounce.effekt 
/home/max-priv/Dokumente/repos/effekt/out/bounce.js:606
                                    return tmp1351_1353().then(((tmp872_1298) =>
                                    ^

ReferenceError: tmp1351_1353 is not defined
    at /home/max-priv/Dokumente/repos/effekt/out/bounce.js:606:37
    at /home/max-priv/Dokumente/repos/effekt/out/bounce.js:568:32
    at tmp1251_1293 (/home/max-priv/Dokumente/repos/effekt/out/bounce.js:578:23)
    at /home/max-priv/Dokumente/repos/effekt/out/bounce.js:581:20
    at Object.apply (/home/max-priv/Dokumente/repos/effekt/out/bounce.js:252:19)
    at trampoline (/home/max-priv/Dokumente/repos/effekt/out/bounce.js:166:19)
    at Object.run (/home/max-priv/Dokumente/repos/effekt/out/bounce.js:279:18)
    at [eval]:1:35
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:307:38)

Node.js v18.16.1
Exception in thread "main" java.lang.RuntimeException: Nonzero exit value: 1
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:164)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:121)
        at effekt.Runner.exec(Runner.scala:63)
        at effekt.Runner.exec$(Runner.scala:13)
        at effekt.JSRunner$.exec(Runner.scala:83)
        at effekt.JSRunner$.eval(Runner.scala:100)
        at effekt.JSRunner$.eval(Runner.scala:96)
        at effekt.Driver.compileSource$$anonfun$1(Driver.scala:86)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.Option.foreach(Option.scala:437)
        at effekt.Driver.compileSource(Driver.scala:86)
        at effekt.Driver.compileSource$(Driver.scala:25)
        at effekt.Server$.compileSource(Server.scala:263)
        at effekt.Server$.compileSource(Server.scala:263)
        at kiama.util.Compiler.compileFile(Compiler.scala:102)
        at kiama.util.Compiler.compileFile$(Compiler.scala:22)
        at effekt.Server$.compileFile(Server.scala:263)
        at effekt.Driver.run$$anonfun$1(Driver.scala:45)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at effekt.Driver.run(Driver.scala:46)
        at effekt.Driver.run$(Driver.scala:25)
        at effekt.Server$.run(Server.scala:263)
        at effekt.Server$.run(Server.scala:263)
        at kiama.util.Compiler.driver(Compiler.scala:86)
        at kiama.util.Compiler.driver$(Compiler.scala:22)
        at effekt.Server$.driver(Server.scala:263)
        at kiama.util.Compiler.main(Compiler.scala:50)
        at kiama.util.Compiler.main$(Compiler.scala:22)
        at effekt.Server$.main(Server.scala:263)
        at effekt.Server.main(Server.scala)
max-priv@NOAH367-L:~/Dokumente/repos/effekt$ 
```

compiled js file and effekt file:
[bounce_bug.zip](https://github.com/effekt-lang/effekt/files/13340197/bounce_bug.zip)

the file uses an import, so it might be worth using my effekt-fork where it lives:
https://github.com/IR0NSIGHT/fasteffekt/pull/17/commits/a48ee0d397ecd996d42df1bdd7165cdeb008d27c

**Comment by IR0NSIGHT** [comment]
```
import examples/fasteffekt/benchmark
import mutable/array
// class Ball {
//   constructor(random) {
//     this.x = random.next() % 500;
//     this.y = random.next() % 500;
//     this.xVel = (random.next() % 300) - 150;
//     this.yVel = (random.next() % 300) - 150;
//   }
record Ball(
    x: Double,
    y: Double,
    xVel: Double,
    yVel: Double
)

def randomBall(){ next: () => Int }: Ball = {
    Ball(
        toDouble(mod(next(),500)),
        toDouble(mod(next(),500)),
        toDouble(mod(next(),300)-150),
        toDouble(mod(next(),300)-150)
    )
}

def abs(n: Double): Double = if (n < 0.0) 0.0 - n else n

//   bounce() {
//     const xLimit = 500;
//     const yLimit = 500;
//     let bounced = false;

//     this.x += this.xVel;
//     this.y += this.yVel;

//     if (this.x > xLimit) {
//       this.x = xLimit; this.xVel = 0 - Math.abs(this.xVel); bounced = true;
//     }

//     if (this.x < 0) {
//       this.x = 0; this.xVel = Math.abs(this.xVel); bounced = true;
//     }

//     if (this.y > yLimit) {
//       this.y = yLimit; this.yVel = 0 - Math.abs(this.yVel); bounced = true;
//     }

//     if (this.y < 0) {
//       this.y = 0; this.yVel = Math.abs(this.yVel); bounced = true;
//     }

//     return bounced;
//   }
// }
def bounce(ball: Ball): Tuple2[Ball, Boolean] = {
    val xLimit = 500.0;
    val yLimit = 500.0;
    var bounced = false;
    var x = ball.x + ball.xVel;
    var y = ball.y + ball.yVel;
    var xVel = ball.xVel;
    var yVel = ball.yVel;

    if (x > xLimit) {
        x = xLimit; 
        xVel = 0.0 - abs(xVel);
        bounced = true;
    }
    if (x < 0.0) {
        x = 0.0;
        xVel = abs(xVel)
        bounced = true;
    }
    if (y > yLimit) {
        y = yLimit;
        yVel = 0.0 - abs(yVel);
        bounced = true;
    }
    if (y < 0.0) {
        y = 0.0;
        yVel = abs(yVel);
        bounced = true;
    }
    (Ball(x,y, xVel, yVel), bounced)
}

def bitAnd(x: Int, y: Int) = mod(x,(y+1)) 



// class Random {
//   constructor() {
//     this.seed = 74755;
//   }

//   next() {
//     this.seed = ((this.seed * 1309) + 13849) & 65535;
//     return this.seed;
//   }
// }



def Bounce(iterations: Int) = {
    def verifyResult(result: Int) =
        true;
        //result == 1331

    var seed = 74755;
    def next(): Int = {
        seed = bitAnd((seed * 1309) + 13849, 65535);
        seed;
    }

    def benchmark(): Int = {
        //FIXME: uncommenting this line breaks the compiler.
        val random = next();

        val ballCount = 100;
        var bounces = 0;
        val balls = emptyArray[Ball]()
        each(0, ballCount){ i => 
            val rBall = randomBall(){next}
            put(balls, i, rBall)
            println(rBall)
        }


        each(0, 50) { i => 
            each(0, ballCount) { i => 
                val ball = balls.unsafeGet(i);
                val (bouncedBall, didBounce) = bounce(ball);
                put(balls, i, bouncedBall);
                if (didBounce)
                    bounces = bounces + 1;
            }
        }
        
        println("bounces="++show(bounces));
        return bounces;
    }  
    
    innerBenchmarkLoop(iterations){benchmark}{verifyResult}
    //println(show(randomBall(){next}))
    //1;
}

def main() = {
    Bounce(1)
}
// def benchmark(): Int = {
//     val random = new som.Random();
//     const ballCount = 100;
//     let bounces = 0;
//     const balls = new Array(ballCount);
//     let i = 0;

//     for (i = 0; i < ballCount; i += 1) {
//       balls[i] = new Ball(random);
//     }

//     for (i = 0; i < 50; i += 1) {
//       for (const ball of balls) {
//         if (ball.bounce()) {
//           bounces += 1;
//         }
//       }
//     }
//     return bounces;
//   }



``

**Comment by b-studios** [comment]
Can you try to [minimize](https://stackoverflow.com/help/minimal-reproducible-example) the example?

**Comment by IR0NSIGHT** [comment]
Noted, will try to minimize as soon as i find some time for it :+1:

**Comment by b-studios** [comment]
Here is the minimized example

```
def randomBall(){ next: () => Int }: Int =
  mod(next(), 500) + mod(next(), 500)

def Bounce(iterations: Int) = {
  def next(): Int = 42

  def benchmark(): Unit = {
      // NOTE: uncommenting the following line fixes the bug.
      //val random = next();

      each(0, 10){ i => println(randomBall(){next}) }
  }

  benchmark();
  benchmark()
}

def main() = Bounce(1)
```

**Comment by b-studios** [comment]
@IR0NSIGHT could you check that the hotfix I pushed also resolves your original issue?

**Comment by IR0NSIGHT** [comment]
> @IR0NSIGHT could you check that the hotfix I pushed also resolves your original issue?

it does indeed fix the issue, thanks a lot!
