### ISSUE TITLE
Workflow runs flaky / "Text file busy"

### ISSUE THREAD

**Issue by marzipankaiser** [effekt-lang/effekt#322]
In both the workflow runs
- (#320) https://github.com/effekt-lang/effekt/actions/runs/7034447758/job/19142525276?pr=321  |  https://github.com/effekt-lang/effekt/actions/runs/7034447758/job/19142525276?pr=321#step:9:208
- (#321) https://github.com/effekt-lang/effekt/actions/runs/7019874175/job/19098324052  |  https://github.com/effekt-lang/effekt/actions/runs/7019874175/job/19098324052#step:9:197
one of the tests fails with something like
```
==> X effekt.ChezScheme*Tests.examples/pos/multieffects.effekt (chez-callcc)  2.115s java.io.IOException: Cannot run program "*": error=26, Text file busy
```

This is probably a chance event, and might be related to https://bugs.openjdk.org/browse/JDK-8068370.
Leaving this here because it occured in both of my last PRs, so we might want to look into this if this stays this frequent for more than two runs.

**Comment by marzipankaiser** [comment]
#323: https://github.com/effekt-lang/effekt/actions/runs/7046569951/job/19178631771#step:9:116

**Comment by b-studios** [comment]
Strange, I also just ran into this issue: 

```
java.io.IOException: Cannot run program "/home/runner/work/effekt/effekt/./out/tests/effekt.chezschemelifttests/examples_pos_multieffects": error=26, Text file busy
```

**Comment by jiribenes** [comment]
Very much worth fixing, in fact. :)

**Comment by jiribenes** [comment]
https://github.com/effekt-lang/effekt/actions/runs/8391413168/job/22981712695
This error was also detected in REPLTests now.
```
==> X effekt.ReplTests.Evaluating small examples  10.147s java.io.IOException: Cannot run program "/home/runner/work/effekt/effekt/./out/interactive": error=26, Text file busy
[53](https://github.com/effekt-lang/effekt/actions/runs/8391413168/job/22981712695#step:9:54)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[54](https://github.com/effekt-lang/effekt/actions/runs/8391413168/job/22981712695#step:9:55)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[55](https://github.com/effekt-lang/effekt/actions/runs/8391413168/job/22981712695#step:9:56)
    at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:85)
[56](https://github.com/effekt-lang/effekt/actions/runs/8391413168/job/22981712695#step:9:57)
    at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:119)
[57](https://github.com/effekt-lang/effekt/actions/runs/8391413168/job/22981712695#step:9:58)
    at effekt.Runner.eval(Runner.scala:70)
[58](https://github.com/effekt-lang/effekt/actions/runs/8391413168/job/22981712695#step:9:59)
    at effekt.Runner.eval$(Runner.scala:14)
[59](https://github.com/effekt-lang/effekt/actions/runs/8391413168/job/22981712695#step:9:60)
    at effekt.JSRunner$.eval(Runner.scala:107)
    [...]
```

**Comment by jiribenes** [comment]
I've just noticed Text file busy on the JS backend in #695:
https://github.com/effekt-lang/effekt/actions/runs/12526375324/job/34938863414?pr=695#step:11:589
![Screenshot_20241228-130527](https://github.com/user-attachments/assets/8564b4e4-72ef-4dda-88f9-77f81c41ef48)

**Comment by jiribenes** [comment]
Again seen on the JS backend in #937:
https://github.com/effekt-lang/effekt/actions/runs/14495310033/job/40662358029#step:4:192

<img width="913" alt="Image" src="https://github.com/user-attachments/assets/f409e9ea-241b-4637-9b45-ec0d25986c50" />

**Comment by jiribenes** [comment]
https://github.com/effekt-lang/effekt/actions/runs/16073960505/job/45364686057?pr=1070#step:4:308
Fun, "text file busy" on two different JS files -- one importing the other [!], in #1070

**Comment by jiribenes** [comment]
Again seen on JS (current master, 5193c3d)
https://github.com/effekt-lang/effekt/actions/runs/17586326487/job/49955179055#step:4:1042

<img width="402" height="88" alt="Image" src="https://github.com/user-attachments/assets/497f779d-4b28-4ee7-a627-34eb3feb8474" />
