### ISSUE TITLE
WebTests might not be reliable

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#558]
In https://github.com/effekt-lang/effekt/pull/542 (in commit https://github.com/effekt-lang/effekt/pull/542/commits/157a005599989c5ac18a308c1d3fb5c64daa11f0 or some previous one), the WebTests seemed to throw errors, but the tests still registered as passing, even though they should have failed by the virtue of erroring:
```
+ effekt.WebTests.Can read files from the stdlib 8ms  
/home/runner/work/effekt/effekt/out/tests/effekt.javascripttests/lib_test.js:854
              const v_r_5457733111_546489 = Math.round(performance.now() * 1000000);
                                                       ^
ReferenceError: performance is not defined
    at /home/runner/work/effekt/effekt/out/tests/effekt.javascripttests/lib_test.js:854:56
    at /home/runner/work/effekt/effekt/out/tests/effekt.javascripttests/lib_test.js:856:15
    at Object.apply (/home/runner/work/effekt/effekt/out/tests/effekt.javascripttests/lib_test.js:515:19)
    at trampoline (/home/runner/work/effekt/effekt/out/tests/effekt.javascripttests/lib_test.js:435:19)
    at Object.run (/home/runner/work/effekt/effekt/out/tests/effekt.javascripttests/lib_test.js:542:18)
    at Object.main (/home/runner/work/effekt/effekt/out/tests/effekt.javascripttests/lib_test.js:1095:29)
    at Object.<anonymous> (/home/runner/work/effekt/effekt/out/tests/effekt.javascripttests/lib_test:2:89)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
+ effekt.WebTests.Evaluate simple expressions in REPL 14384ms  
42
+ effekt.WebTests.Evaluate expressions that uses a builtin which relies on an extern literal 14812ms  [object Object]
+ effekt.WebTests.Evaluate expressions using stdlib in REPL 11153ms  
+ effekt.WebTests.Show core on website 10711ms  
+ effekt.WebTests.Load file with multiline extern strings 12618ms  
Error: /home/runner/work/effekt/effekt/out/tests/effekt.mltests/lib_test.sml 391.69-391.76.
  String constant with character too large for type: #"\u2715".
    type: string
Error: /home/runner/work/effekt/effekt/out/tests/effekt.mltests/lib_test.sml 561.67-561.74.
  String constant with character too large for type: #"\u2713".
    type: string
```

Note that this might have been a fluke introduced by me reading the interspersed logs. In that case, feel free to close this issue as invalid.

**Comment by jiribenes** [comment]
I thought about this more, tried out some things locally, and I really think it was just a fluke (as evidenced by the files the errors are coming from).
Closing (but please reopen if you re-encounter this problem!)
