### ISSUE TITLE
Repl crashes when redefining name

### ISSUE THREAD

**Issue by b-studios** [effekt-lang/effekt#77]
The following repl session crashes:
```
val x = 1 // enter
val x = 1 // enter
```

with the following stack trace
```
[error] Internal Compiler Error: Cannot find symbol for IdDef(x)
[error] 	at effekt.util.messages$CompilerPanic$.apply(Messages.scala:24)
[error] 	at effekt.util.messages$ErrorReporter.panic(Messages.scala:59)
[error] 	at effekt.util.messages$ErrorReporter.panic$(Messages.scala:50)
[error] 	at effekt.context.Context.panic(Context.scala:40)
[error] 	at effekt.util.messages$ErrorReporter.panic(Messages.scala:58)
[error] 	at effekt.util.messages$ErrorReporter.panic$(Messages.scala:50)
[error] 	at effekt.context.Context.panic(Context.scala:40)
[error] 	at effekt.context.AnnotationsDB.symbolOf$$anonfun$1(Annotations.scala:366)
[error] 	at scala.Option.getOrElse(Option.scala:201)
```

**Comment by marzipankaiser** [comment]
This only seems to happens with _identical_ definitions.
The following runs fine for me:
```effekt
val x = 1 // enter
val x = 2 // enter
```

**Comment by b-studios** [comment]
Interesting! Maybe it is a problem with the parser caching things?

**Comment by marzipankaiser** [comment]
Could be. I just tested it, and even this runs fine:
```effekt
val x = 1 // with whitespace after =
val x =1 // without whitespace after =
```
